CREATE DATABASE ZOMATO;
USE DATABASE ZOMATO



CREATE OR REPLACE TABLE goldusers_signup
(
userid integer,
gold_signup_date date); 


INSERT INTO goldusers_signup VALUES (1,'2017-09-22'),(3,'2017-04-21');



CREATE OR REPLACE TABLE users
(
userid integer,
signup_date date);


INSERT INTO users VALUES 
(1,'2014-09-02'),
(2,'2015-01-15'),
(3,'2014-04-11');



CREATE OR REPLACE TABLE sales
(
userid integer,
created_date date,
product_id integer); 


INSERT INTO sales VALUES 
(1,'2017-04-19',2),
(3,'2019-12-18',1),
(2,'2020-07-20',3),
(1,'2019-10-23',2),
(1,'2018-03-19',3),
(3,'2016-12-20',2),
(1,'2016-11-09',1),
(1,'2016-05-20',3),
(2,'2017-09-24',1),
(1,'2017-03-11',2),
(1,'2016-03-11',1),
(3,'2016-11-10',1),
(3,'2017-12-07',2),
(3,'2016-12-15',2),
(2,'2017-11-08',2),
(2,'2018-09-10',3);



CREATE OR REPLACE TABLE product
(
product_id integer,
product_name text,
price integer
); 


INSERT INTO product VALUES
(1,'p1',980),
(2,'p2',870),
(3,'p3',330);



SELECT * FROM ZOMATO.PUBLIC.GOLDUSERS_SIGNUP;
SELECT * FROM ZOMATO.PUBLIC.PRODUCT;
SELECT * FROM ZOMATO.PUBLIC.SALES;
SELECT * FROM ZOMATO.PUBLIC.USERS;



---***QUESTION 1: WHAT IS THE TOTAL AMOUNT EACH CUSTOMER  SPENT ON ZOMATO?***---


SELECT S.USERID AS CUSTOMER, SUM(P.PRICE) AS TOTAL_SALES
FROM SALES AS S
JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1
ORDER BY 1;   



---***QUESTION 2: HOW MANY DAYS HAS EACH CUSTOMER VISITED ZOMATO?***---


SELECT USERID,COUNT(CREATED_DATE) AS VISIT_COUNT
FROM SALES
GROUP BY 1
ORDER BY 1;



---***QUESTION 3: WHAT WAS THE FIRST PRODUCT PURCHASED BY EACH CUSTOMER?***---

SELECT * FROM
(SELECT *, RANK() OVER (PARTITION BY USERID ORDER BY CREATED_DATE) RANK
FROM SALES)
WHERE RANK = 1



---***QUESTION 4: WHAT IS THE MOST PURCHASED ITEM ON THE MENU AND HOW MANY TIMES WAS IT PURCHASED BY ALL CUSTOMERS?***---


SELECT USERID, PRODUCT_ID,COUNT(PRODUCT_ID) FROM SALES 
WHERE PRODUCT_ID = 
(SELECT PRODUCT_ID
FROM SALES
GROUP BY PRODUCT_ID
ORDER BY COUNT(PRODUCT_ID) DESC LIMIT 1)
GROUP BY 1,2
ORDER BY 1;



---***QUESTION 5: WHICH ITEM WAS THE MOST POPULAR FOR EACH OF THE CUSTOMER?***---


SELECT *
FROM
(SELECT USERID, PRODUCT_ID,COUNT(PRODUCT_ID) AS OCCURRENCE,RANK() OVER (PARTITION BY USERID ORDER BY OCCURRENCE DESC) AS OCCURRENCE_RANK
FROM SALES
GROUP BY 1,2
ORDER BY 1,3 DESC)
WHERE OCCURRENCE_RANK = 1;



---***QUESTION 6: WHICH ITEM WAS PURCHASED FIRST BY THE CUSTOMER AFTER THEY BECAME A MEMBER?***---


SELECT * FROM
(SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,G.GOLD_SIGNUP_DATE, RANK() OVER (PARTITION BY S.USERID ORDER BY CREATED_DATE) AS RNK
FROM SALES AS S
INNER JOIN GOLDUSERS_SIGNUP AS G
ON S.USERID = G.USERID
WHERE G.GOLD_SIGNUP_DATE < S.CREATED_DATE)
WHERE RNK = 1



---***QUESTION 7: WHICH ITEM WAS PURCHASED JUST BEFORE THE CUSTOMER BECAME A MEMBER?***---


SELECT * FROM
(SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,G.GOLD_SIGNUP_DATE, RANK() OVER (PARTITION BY S.USERID ORDER BY CREATED_DATE DESC) AS RNK
FROM SALES AS S
INNER JOIN GOLDUSERS_SIGNUP AS G
ON S.USERID = G.USERID
WHERE G.GOLD_SIGNUP_DATE >= S.CREATED_DATE)
WHERE RNK = 1



---***QUESTION 8: WHAT IS THE TOTAL ORDERS AND AMOUNT SPENT FOR EACH MEMBER BEFORE THEY BECAME MEMBER?***---


WITH ABC(USERID,CREATED_DATE,PRODUCT_ID,GOLD_SIGNUP_DATE,PRODUCT_NAME,PRICE)
AS
(SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,G.GOLD_SIGNUP_DATE,P.PRODUCT_NAME,P.PRICE
FROM SALES AS S
INNER JOIN GOLDUSERS_SIGNUP AS G
ON S.USERID = G.USERID
LEFT OUTER JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE G.GOLD_SIGNUP_DATE >= S.CREATED_DATE)
SELECT USERID,GOLD_SIGNUP_DATE,COUNT(CREATED_DATE) AS TOTAL_ORDERS_PURCHASED, SUM(PRICE) AS TOTAL_AMOUNT_SPENT
FROM ABC
GROUP BY 1,2



---***QUESTION 9: IF BUYING EACH PRODUCT GENERATES POINTS FOR e.g 5RS = 2 ZOMATO POINTS AND EACH PRODUCT HAS DIFFERENT PURCHASING POINTS FOR e.g FOR  P1 5RS =1 ZOMATO POINT,  FOR P2 10RS = 5 ZOMATO POINTS AND P3 5RS = 1 ZOMATO POINTS.
---**CALCULATE POINTS COLLECTED BY EACH CUSTOMERS AND FOR WHICH PRODUCT MOST POINTS HAVE BEEN GIVEN TILL NOW ?***---


--SOLUTION PART-1 :

SELECT USERID,SUM(ZOMATO_POINTS) AS TOTAL_POINTS_EARNED,SUM(ZOMATO_POINTS)*2.5 AS TOTAL_MONEY_EARNED
FROM
(WITH ZP (USERID,CREATED_DATE,PRODUCT_ID,PRODUCT_NAME,PRICE)
AS
(SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,P.PRODUCT_NAME,P.PRICE FROM SALES AS S
LEFT JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID)
SELECT *,
CASE
WHEN PRODUCT_NAME = 'p1' THEN ROUND((PRICE/5),2) 
WHEN PRODUCT_NAME = 'p2' THEN ROUND((PRICE/2),2)
WHEN PRODUCT_NAME = 'p3' THEN ROUND((PRICE/5),2)
END AS ZOMATO_POINTS
FROM ZP)
GROUP BY 1
ORDER BY 2 DESC


--SOLUTION PART-2 :


SELECT PRODUCT_NAME,SUM(ZOMATO_POINTS)
FROM
(WITH ZP (USERID,CREATED_DATE,PRODUCT_ID,PRODUCT_NAME,PRICE)
AS
(SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,P.PRODUCT_NAME,P.PRICE FROM SALES AS S
LEFT JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID)
SELECT *,
CASE
WHEN PRODUCT_NAME = 'p1' THEN ROUND((PRICE/5),2) 
WHEN PRODUCT_NAME = 'p2' THEN ROUND((PRICE/2),2)
WHEN PRODUCT_NAME = 'p3' THEN ROUND((PRICE/5),2)
END AS ZOMATO_POINTS
FROM ZP)
GROUP BY 1
ORDER BY 2 DESC LIMIT 1




---***QUESTION 10: IN THE FIRST YEAR AFTER A CUSTOMER JOINS THE GOLD PROGRAM(INCLUDING THEIR JOIN DATE) IRRESPECTIVE OF WHAT THE CUSTOMER HAS PURCHASED THEY EARN 5 ZOMATO POINTS FOR EVERY 10RS SPENT. WHO EARNED MORE 1 OR 3? AND WHAT WAS THEIR POINTS EARNINGS IN THEIR FIRST YEAR?***---


SELECT USERID,PRICE*0.5 AS TOTAL_POINTS FROM
(SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,G.GOLD_SIGNUP_DATE,P.PRODUCT_NAME,P.PRICE,S.CREATED_DATE - G.GOLD_SIGNUP_DATE AS DATE_DIFF
FROM SALES AS S
INNER JOIN GOLDUSERS_SIGNUP AS G
ON S.USERID = G.USERID
LEFT OUTER JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE DATE_DIFF >=0 and DATE_DIFF <= 365)
GROUP BY 1,2;




---***QUESTION 11: RANK ALL THE TRANSACTIONS OF THE CUSTOMER?***---


SELECT S.USERID,S.CREATED_DATE,S.PRODUCT_ID,P.PRODUCT_NAME,P.PRICE,DENSE_RANK() OVER (PARTITION BY USERID ORDER BY PRICE,CREATED_DATE) RNK FROM SALES AS S
LEFT JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID




---***QUESTION 12: RANK ALL THE TRANSACTIONS FOR EACH MEMBER WHENEVER THEY ARE A ZOMATO GOLD MEMBER FOR EVERY NON GOLD MEMBER TRANSACTION MARK AS NA?***-


SELECT A.* , CASE
WHEN RNK = 0 THEN 'NA' ELSE RNK END AS RRNK FROM
(SELECT *,CAST((CASE
WHEN GOLD_SIGNUP_DATE IS NULL THEN 0 ELSE                
RANK() OVER (PARTITION BY S.USERID ORDER BY CREATED_DATE DESC) END)AS VARCHAR) AS RNK
FROM SALES AS S
LEFT JOIN GOLDUSERS_SIGNUP AS G
ON S.USERID = G.USERID and CREATED_DATE >= GOLD_SIGNUP_DATE) AS A
